web:
  context: /monitoring

tasks:
  Backgroundable:
    concurrency: 0

ruby:
  version: 1.9
  compile_mode: force

jobs:
  monitoring.get_stats:
    description:  "get stats and push them to zabbix server"
    job:          MonitoringJob
    cron:         '0 */5 * * * ?'
    singleton:    false
    config:
      host: 'zabbix.nokaut'
      port: '20051'
      debug: false

environment:
  ZABBIX_STRIP_HOST: .nokaut
